create table if not exists public.meal_projects (
  id bigint generated by default as identity primary key,
  office_code text not null,
  school_code text not null,
  school_name text,
  month text not null,
  password_salt text not null,
  password_hash text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(office_code, school_code, month)
);
alter table public.meal_projects enable row level security;
