import * as XLSX from 'xlsx';import QRCode from 'qrcode';import './style.css';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const A={1:'난류',2:'우유',3:'메밀',4:'땅콩',5:'대두',6:'밀',7:'고등어',8:'게',9:'새우',10:'돼지고기',11:'복숭아',12:'토마토',13:'아황산염',14:'호두',15:'닭고기',16:'소고기',17:'오징어',18:'조개류',19:'잣'};
const p=new URLSearchParams(location.search);let school=JSON.parse(localStorage.getItem('meal_school')||'null'),month=p.get('month')||new Date().toISOString().slice(0,7),data={},date='',tab='month',allergies=new Set(JSON.parse(localStorage.getItem('allergies')||'[]')),allergyOn=localStorage.getItem('allergyOn')==='1',source='api';
const signage=p.get('mode')==='signage';if(p.get('office'))school={officeCode:p.get('office'),schoolCode:p.get('school'),schoolName:p.get('name')||'학교 급식'};
window.addEventListener('DOMContentLoaded',()=>signage?bootSignage():renderHome());
function renderHome(){app.innerHTML=`<div class="shell"><header><div class="logo">🥗</div><div><h1>스마트 월간식단 뷰어</h1><p>API 또는 엑셀로 불러오고 수정본을 사이니지에 표시합니다.</p></div>${school?`<button id="change" class="ghost">학교 변경</button>`:''}</header>${school?workspace():landing()}<div id="modal" class="modal hide"></div></div>`;bind()}
function landing(){return `<section class="landing"><h2>식단 불러오기</h2><div class="source"><button id="apiMode"><b>나이스 API</b><span>학교 검색으로 자동 불러오기</span></button><label><b>월간식단 엑셀 업로드</b><span>학교 파일을 직접 분석</span><input id="excel" type="file" accept=".xlsx,.xls"></label></div><div class="search"><input id="q" placeholder="학교명 입력"><button id="find">학교 검색</button></div><div id="results"></div></section>`}
function workspace(){return `<section class="toolbar"><div><small>${source==='api'?'나이스 API':'엑셀 업로드'}</small><h2>${esc(school.schoolName)}</h2></div><input id="month" type="month" value="${month}"><button id="reload" class="primary">식단 불러오기</button><button id="filter" class="danger">🚨 알레르기</button><button id="signage" class="dark">사이니지</button></section><nav>${[['month','월간 식단'],['day','오늘의 식단'],['edit','월 전체 편집'],['detail','상세 편집']].map(x=>`<button data-tab="${x[0]}" class="${tab===x[0]?'active':''}">${x[1]}</button>`).join('')}</nav><main id="content"><div class="loading">식단을 불러오는 중입니다.</div></main>`}
function bind(){if($('#change'))$('#change').onclick=()=>{localStorage.removeItem('meal_school');school=null;data={};renderHome()};if($('#find')){$('#find').onclick=findSchools;$('#q').onkeydown=e=>e.key==='Enter'&&findSchools()}if($('#excel'))$('#excel').onchange=loadExcel;if($('#reload'))$('#reload').onclick=loadApi;if($('#month'))$('#month').onchange=e=>{month=e.target.value;loadApi()};if($('#filter'))$('#filter').onclick=openFilter;if($('#signage'))$('#signage').onclick=openSignage;$$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));renderTab()});if(school&&source==='api')loadApi()}
async function findSchools(){const q=$('#q').value.trim();if(q.length<2)return alert('두 글자 이상 입력하세요.');$('#results').innerHTML='검색 중…';const r=await fetch('/api/schools?q='+encodeURIComponent(q)),j=await r.json();$('#results').innerHTML=j.map((s,i)=>`<button class="school" data-i="${i}"><b>${esc(s.schoolName)}</b><span>${esc(s.officeName)} · ${esc(s.address)}</span></button>`).join('');$$('.school').forEach(b=>b.onclick=()=>{school=j[+b.dataset.i];source='api';localStorage.setItem('meal_school',JSON.stringify(school));renderHome()})}
async function loadApi(){try{$('#content').innerHTML='<div class="loading">나이스 식단을 불러오는 중입니다.</div>';const r=await fetch(`/api/meals?office=${school.officeCode}&school=${school.schoolCode}&month=${month.replace('-','')}`),rows=await r.json();if(!r.ok)throw Error(rows.error);data=parseRows(rows);await applySaved();setDefaultDate();renderTab()}catch(e){$('#content').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function parseRows(rows){const out={};rows.filter(r=>r.mealCode==='2').forEach(r=>{const d=`${r.date.slice(0,4)}-${r.date.slice(4,6)}-${r.date.slice(6,8)}`;const items=r.dishes.split('<br/>').map(parseDish).filter(Boolean);const nutrient={};r.nutrients.split('<br/>').forEach(x=>{const m=x.match(/^(.+?)\s*:\s*([\d.]+)\s*(.*)$/);if(m)nutrient[m[1].trim()]={value:m[2],unit:m[3]}});out[d]={date:d,items,calories:r.calories,nutrient,note:'',edited:false}});return out}
function parseDish(t){t=t.replace(/<[^>]+>/g,'').trim();if(!t)return null;const al=[];for(const m of t.matchAll(/\(([\d.]+)\)/g))m[1].split('.').map(Number).forEach(n=>n>=1&&n<=19&&al.push(n));let name=t.replace(/\(([\d.]+)\)/g,'').trim(),type=/자율/.test(name)?'self':'normal';return{name,allergy:[...new Set(al)],type,category:'',order:0}}
async function applySaved(){try{const r=await fetch(`/api/project?office=${school.officeCode}&school=${school.schoolCode}&month=${month}`),j=await r.json();if(j?.payload?.days)data=j.payload.days}catch{}}
function setDefaultDate(){const today=new Date().toISOString().slice(0,10);date=data[today]?today:Object.keys(data).sort()[0]||''}
async function loadExcel(e){const f=e.target.files[0];if(!f)return;const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});data={};let cur='';for(const row of rows){const text=row.filter(Boolean).join(' ');const dm=text.match(/(\d{1,2})\s*[월./-]\s*(\d{1,2})\s*일?/);if(dm)cur=`${new Date().getFullYear()}-${String(dm[1]).padStart(2,'0')}-${String(dm[2]).padStart(2,'0')}`;if(cur&&row.length){const candidates=row.map(String).filter(x=>x&&x.length>2&&!/월간|식단|영양|에너지|단백질|칼슘|철/.test(x));if(candidates.length){data[cur]??={date:cur,items:[],calories:'',nutrient:{},note:'',edited:false};candidates.forEach(x=>{if(!data[cur].items.some(i=>i.name===x))data[cur].items.push(parseDish(x))})}}}school={officeCode:'EXCEL',schoolCode:'LOCAL',schoolName:f.name.replace(/\.[^.]+$/,'')};source='excel';month=Object.keys(data)[0]?.slice(0,7)||month;setDefaultDate();renderHome();renderTab()}
function renderTab(){if(!$('#content'))return;({month:renderMonth,day:renderDay,edit:renderEdit,detail:renderDetail}[tab]||renderMonth)()}
function renderMonth(){const cards=Object.keys(data).sort().map(d=>{const x=data[d],dt=new Date(d+'T00:00:00');return `<article class="daycard" data-date="${d}"><div class="daytop"><b>${dt.getMonth()+1}월 ${dt.getDate()}일 ${'일월화수목금토'[dt.getDay()]}요일</b>${x.edited?'<span>수정됨</span>':''}</div>${x.items.map((i,k)=>`<div class="mrow ${i.type}">${icon(i.name)} ${esc(i.name)} ${i.allergy.length?`<small>${i.allergy.join('·')}</small>`:''}</div>`).join('')}<footer>${esc(x.calories||'영양정보 없음')}</footer></article>`}).join('');$('#content').innerHTML=`<div class="monthhead"><h2>${month} 전체 식단</h2><button class="ghost">전체 식단 카드</button></div><section class="monthgrid">${cards||'<div class="empty">식단이 없습니다.</div>'}</section>`;$$('.daycard').forEach(c=>c.onclick=()=>{date=c.dataset.date;tab='day';$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab==='day'));renderDay()})}
function renderDay(){const x=data[date];if(!x)return $('#content').innerHTML='<div class="empty">식단이 없습니다.</div>';const dt=new Date(date+'T00:00:00');$('#content').innerHTML=`<section class="daybar"><button id="prev">‹</button><div><h2>${dt.getFullYear()}년 ${dt.getMonth()+1}월 ${dt.getDate()}일</h2><p>${'일월화수목금토'[dt.getDay()]}요일 중식</p></div><button id="next">›</button><button id="today">오늘의 식단</button></section>${filterBanner()}<section class="layout"><div class="dishgrid">${x.items.map(dishCard).join('')}</div><aside><section class="nutrition"><h3>오늘의 영양정보</h3>${nutrition(x)}</section><section class="edu"><h3>💡 오늘의 영양교육</h3>${education(x)}</section></aside></section>`;$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#today').onclick=()=>{const t=new Date().toISOString().slice(0,10);if(data[t]){date=t;renderDay()}else alert('오늘은 등록된 급식이 없습니다.')};}
function dishCard(i){const hit=allergyOn&&i.allergy.some(n=>allergies.has(n));return `<article class="dish ${i.type} ${hit?'warn':''}"><span>${i.type==='choiceA'?'선택급식 A':i.type==='choiceB'?'선택급식 B':i.type==='self'?'자율배식':'MENU'}</span><h3>${icon(i.name)} ${esc(i.name)}</h3><p>${i.allergy.length?'알레르기 '+i.allergy.join('·'):'알레르기 표시 없음'}</p>${hit?'<b class="warnmark">주의</b>':''}</article>`}
function nutrition(x){const keys=['단백질','칼슘','철분'];return `<div class="nut"><span>에너지</span><b>${esc(x.calories||'-')}</b></div>`+keys.map(k=>`<div class="nut"><span>${k}</span><b>${x.nutrient[k]?`${x.nutrient[k].value} ${x.nutrient[k].unit}`:'-'}</b></div>`).join('')}
function education(x){const names=x.items.map(i=>i.name).join(' '),arr=[];if(/국|찌개|탕|면/.test(names))arr.push(['🧂 나트륨','국물은 적게, 건더기 위주로 먹어요.']);if(/주스|아이스크림|케이크|빵|초콜릿/.test(names))arr.push(['🍭 당류','달콤한 후식은 정량만 먹고 물을 충분히 마셔요.']);if(/샐러드|나물|채소|쌈/.test(names))arr.push(['🥬 식이섬유','채소 반찬을 함께 먹어 장 건강을 지켜요.']);return (arr.length?arr:[['🥗 균형식','다양한 음식을 골고루 먹어요.']]).map(a=>`<div class="eduitem"><b>${a[0]}</b><p>${a[1]}</p></div>`).join('')}
function filterBanner(){if(!allergyOn||!allergies.size)return'';return `<div class="filterbar"><b>🚨 알레르기 필터 적용 중</b>${[...allergies].map(n=>`<span>${n} ${A[n]}</span>`).join('')}</div>`}
function move(n){const ds=Object.keys(data).sort(),i=ds.indexOf(date);if(ds[i+n]){date=ds[i+n];renderDay()}}
function renderEdit(){const rows=Object.keys(data).sort().flatMap(d=>data[d].items.map((i,k)=>`<tr data-d="${d}" data-i="${k}"><td>${d.slice(5)}</td><td><input class="name" value="${esc(i.name)}"></td><td><input class="alg" value="${i.allergy.join(',')}"></td><td><select class="type"><option value="normal">일반</option><option value="choiceA" ${i.type==='choiceA'?'selected':''}>선택 A</option><option value="choiceB" ${i.type==='choiceB'?'selected':''}>선택 B</option><option value="self" ${i.type==='self'?'selected':''}>자율배식</option></select></td><td><button class="ghost saveRow">적용</button></td></tr>`)).join('');$('#content').innerHTML=`<section class="editor"><div class="edithead"><h2>월 전체 편집</h2><div><button id="replace" class="ghost">찾아 바꾸기</button><button id="saveAll" class="primary">전체 저장</button></div></div><div class="table"><table><thead><tr><th>날짜</th><th>메뉴명</th><th>알레르기</th><th>표시</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section>`;$$('.saveRow').forEach(b=>b.onclick=()=>applyRow(b.closest('tr')));$('#replace').onclick=replaceAll;$('#saveAll').onclick=saveProject}
function applyRow(tr){const x=data[tr.dataset.d].items[+tr.dataset.i];x.name=tr.querySelector('.name').value;x.allergy=tr.querySelector('.alg').value.split(',').map(Number).filter(n=>n>=1&&n<=19);x.type=tr.querySelector('.type').value;data[tr.dataset.d].edited=true}
function replaceAll(){const a=prompt('찾을 내용'),b=a!==null?prompt('바꿀 내용',''):null;if(a===null||b===null)return;Object.values(data).forEach(d=>d.items.forEach(i=>{i.name=i.name.split(a).join(b)}));renderEdit()}
function renderDetail(){if(!date)setDefaultDate();const x=data[date];$('#content').innerHTML=`<section class="editor"><div class="edithead"><h2>${date} 상세 편집</h2><button id="detailSave" class="primary">이 날짜 저장</button></div><textarea id="note" placeholder="오늘의 안내문">${esc(x?.note||'')}</textarea><p>메뉴 추가·삭제와 세부 편집은 월 전체 편집에서 진행합니다.</p></section>`;$('#detailSave').onclick=()=>{x.note=$('#note').value;x.edited=true;saveProject()}}
async function saveProject(){$$('tbody tr').forEach(applyRow);const password=prompt('이 학교의 편집 비밀번호를 입력하세요. 처음 저장할 때 설정됩니다.');if(!password)return;const r=await fetch('/api/project',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({office:school.officeCode,school:school.schoolCode,schoolName:school.schoolName,month,password,payload:{days:data}})}),j=await r.json();alert(r.ok?'저장되었습니다.':j.error)}
function openFilter(){const m=$('#modal');m.classList.remove('hide');m.innerHTML=`<div class="modalcard"><h2>알레르기 필터</h2><div class="allergy">${Object.entries(A).map(([n,v])=>`<button data-a="${n}" class="${allergies.has(+n)?'on':''}"><b>${n}</b>${v}</button>`).join('')}</div><button id="toggle" class="${allergyOn?'danger':'ghost'}">${allergyOn?'필터 켜짐':'필터 꺼짐'}</button><button id="done" class="primary">완료</button></div>`;$$('[data-a]').forEach(b=>b.onclick=()=>{allergies.has(+b.dataset.a)?allergies.delete(+b.dataset.a):allergies.add(+b.dataset.a);b.classList.toggle('on')});$('#toggle').onclick=()=>{allergyOn=!allergyOn;$('#toggle').textContent=allergyOn?'필터 켜짐':'필터 꺼짐';$('#toggle').className=allergyOn?'danger':'ghost'};$('#done').onclick=()=>{localStorage.setItem('allergies',JSON.stringify([...allergies]));localStorage.setItem('allergyOn',allergyOn?'1':'0');m.classList.add('hide');renderTab()}}
function openSignage(){const m=$('#modal');m.classList.remove('hide');m.innerHTML=`<div class="modalcard"><h2>사이니지 형태 선택</h2><div class="devices">${[['tv','📺 TV 16:9'],['standby','🖥️ 스탠바이미'],['kiosk','📱 키오스크 9:16']].map(x=>`<button data-device="${x[0]}">${x[1]}</button>`).join('')}</div><div id="signTools"></div><button id="close" class="ghost">닫기</button></div>`;$$('[data-device]').forEach(b=>b.onclick=()=>showSignTools(b.dataset.device));$('#close').onclick=()=>m.classList.add('hide')}
async function showSignTools(type){const url=`${location.origin}${location.pathname}?mode=signage&type=${type}&office=${school.officeCode}&school=${school.schoolCode}&name=${encodeURIComponent(school.schoolName)}&month=${month}`;$('#signTools').innerHTML=`<canvas id="qr"></canvas><input id="url" value="${esc(url)}" readonly><a href="${url}" target="_blank" class="primary link">전체화면 미리보기</a><button id="copy" class="ghost">URL 복사</button>`;await QRCode.toCanvas($('#qr'),url,{width:180});$('#copy').onclick=()=>navigator.clipboard.writeText(url)}
async function bootSignage(){month=p.get('month')||month;document.body.className=`signage ${p.get('type')||'tv'}`;app.innerHTML=`<div class="public"><header><div class="logo">🥗</div><div><h1>${esc(school.schoolName)} 스마트 급식실</h1><p>건강한 선택으로 즐거운 점심시간을 만들어요!</p></div><button id="publicFilter" class="danger">🚨 알레르기 필터</button></header><nav><button data-public="day" class="active">오늘의 식단</button><button data-public="month">월간 식단</button></nav><main id="content"><div class="loading">식단을 불러오는 중입니다.</div></main><div id="modal" class="modal hide"></div></div>`;$('#publicFilter').onclick=openFilter;$$('[data-public]').forEach(b=>b.onclick=()=>{tab=b.dataset.public;$$('[data-public]').forEach(x=>x.classList.toggle('active',x===b));renderTab()});await loadApi()}
function icon(n){if(/밥|덮밥/.test(n))return'🍚';if(/국|탕|찌개|스프|면/.test(n))return'🥣';if(/김치|깍두기/.test(n))return'🌶️';if(/샐러드|나물|채소|쌈/.test(n))return'🥗';if(/과일|주스|요구르트|아이스크림|빵/.test(n))return'🍎';return'🍽️'}
